### ISSUE TITLE
Offer contribution of source to Clojure

### ISSUE THREAD

**Issue by puredanger** [clojure/clojure-cheatsheets#50]
We are in the midst of transitioning this repo into the org.clojure organization (aka Clojure contrib). All contributors should have a signed Clojure Contributor Agreement on file.

**The next step in the process is to make a public offer of contribution from the contributors. You can do so by replying to this issue with a comment that says "I agree"** for the following statement:

"I offer my contributions to the clojure-cheatsheets library as a Clojure contribution: https://github.com/jafingerhut/clojure-cheatsheets. All work was created wholly by these contributors and I give my permission to release this work under the Clojure Contributor Agreement."

Tagging all contributors: @jafingerhut @arrdem @fogus @bluegray @sky-glenjamin @favila

Thanks all! If you have any questions, please contact me at alex.miller@cognitect.com or reply here.

**Comment by fogus** [comment]
I agree.

**Comment by jfingerh** [comment]
I agree.

**Comment by bluegray** [comment]
I agree

**Comment by arrdem** [comment]
I believe 0 lines I contributed to this repo still exist as the patches all seem to pertain to Grimoire but glad to see this project moving to org.clojure. As such,

I agree.

**Comment by jfingerh** [comment]
@favila @sky-glenjamin Do you agree to the statement in the original comment of this issue?  Thanks.

If there is no response in another week or two, I can remove their commits pretty quickly without much loss of information or functionality.

**Comment by puredanger** [comment]
Just bringing this issue back from the dead in case @favila or @sky-glenjamin want to weigh in...

**Comment by jfingerh** [comment]
Thanks for the reminder.  I believe there are only one or two relatively small commits contributed by those people.  If I undid those in some appropriate manner, we should be legally clear for transferring this project over, true?

If true, is it OK to revert those commits from the latest master?  Or would they need to somehow be removed from the git commit log completely?

**Comment by puredanger** [comment]
I think just reverting would be fine.

**Comment by arrdem** [comment]
Yeah the requirement is that work-as-donated consist only of donated work so dropping commits out is adequate. I think Racket re-implemented stuff to be able to re-license.

**Comment by favila** [comment]
Just noticed this, sorry.

I agree to the following statement:

> I offer my contributions to the clojure-cheatsheets library as a Clojure contribution: [jafingerhut/clojure-cheatsheets](https://github.com/jafingerhut/clojure-cheatsheets). All work was created wholly by these contributors and I give my permission to release this work under the Clojure Contributor Agreement.

**Comment by glenjamin** [comment]
I agree.

Looks like I did this contribution under a different GitHub account.

I'll see if I still have credentials for that one too.

**Comment by jafingerhut** [comment]
Cool.  Looks like we got everyone!

**Comment by puredanger** [comment]
@jafingerhut great! can you add me as an admin to this repo? I think that may be enough for me to transfer.

**Comment by jafingerhut** [comment]
@puredanger I have attempted to add you as a collaborator on this repo.  Not sure if that is sufficient access to do what you want, but you should have an invitation to accept.  If that level of access is not sufficient, let me know.

**Comment by puredanger** [comment]
I guess that's not actually needed or sufficient. You, as owner, will need to go to https://github.com/jafingerhut/clojure-cheatsheets/settings and down to the bottom, then "Transfer ownership" to the `clojure` organization. Rich should be able to accept that tomorrow.

**Comment by jafingerhut** [comment]
Thanks for the instructions.  I attempted to follow them just now, and saw a message in pink at the top of the browser page after trying them that said: "You don’t have the permission to create public repositories on clojure".  If Rich sees the offer of transfer and can accept it, then no worries.  If he doesn't, then perhaps something else is needed.

**Comment by arrdem** [comment]
I think we can close this out now ;)
